// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AppendType.
const (
	AppendTypeCorrection AppendType = "correction"
	AppendTypeSupplement AppendType = "supplement"
)

// Valid indicates whether the value is a known member of the AppendType enum.
func (e AppendType) Valid() bool {
	switch e {
	case AppendTypeCorrection:
		return true
	case AppendTypeSupplement:
		return true
	default:
		return false
	}
}

// Defines values for CommentType.
const (
	CommentTypeCorrection CommentType = "correction"
	CommentTypeFailure    CommentType = "failure"
	CommentTypeSuccess    CommentType = "success"
	CommentTypeSupplement CommentType = "supplement"
)

// Valid indicates whether the value is a known member of the CommentType enum.
func (e CommentType) Valid() bool {
	switch e {
	case CommentTypeCorrection:
		return true
	case CommentTypeFailure:
		return true
	case CommentTypeSuccess:
		return true
	case CommentTypeSupplement:
		return true
	default:
		return false
	}
}

// Defines values for ConflictStatus.
const (
	Open     ConflictStatus = "open"
	Resolved ConflictStatus = "resolved"
)

// Valid indicates whether the value is a known member of the ConflictStatus enum.
func (e ConflictStatus) Valid() bool {
	switch e {
	case Open:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for ConflictType.
const (
	CorrectionConflict ConflictType = "correction_conflict"
	KnowledgeConflict  ConflictType = "knowledge_conflict"
)

// Valid indicates whether the value is a known member of the ConflictType enum.
func (e ConflictType) Valid() bool {
	switch e {
	case CorrectionConflict:
		return true
	case KnowledgeConflict:
		return true
	default:
		return false
	}
}

// Defines values for CurationAction.
const (
	ApplyCorrection CurationAction = "apply_correction"
	Archive         CurationAction = "archive"
	CreateConflict  CurationAction = "create_conflict"
	Downgrade       CurationAction = "downgrade"
	MergeKnowledge  CurationAction = "merge_knowledge"
	MergeSupplement CurationAction = "merge_supplement"
	MergeTags       CurationAction = "merge_tags"
)

// Valid indicates whether the value is a known member of the CurationAction enum.
func (e CurationAction) Valid() bool {
	switch e {
	case ApplyCorrection:
		return true
	case Archive:
		return true
	case CreateConflict:
		return true
	case Downgrade:
		return true
	case MergeKnowledge:
		return true
	case MergeSupplement:
		return true
	case MergeTags:
		return true
	default:
		return false
	}
}

// Defines values for KnowledgeStatus.
const (
	Active   KnowledgeStatus = "active"
	Archived KnowledgeStatus = "archived"
)

// Valid indicates whether the value is a known member of the KnowledgeStatus enum.
func (e KnowledgeStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	default:
		return false
	}
}

// AppendRequest defines model for AppendRequest.
type AppendRequest struct {
	Content string     `json:"content"`
	Type    AppendType `json:"type"`
}

// AppendResponse defines model for AppendResponse.
type AppendResponse struct {
	AppendCount int                `json:"append_count"`
	Id          openapi_types.UUID `json:"id"`
}

// AppendType defines model for AppendType.
type AppendType string

// BrowseRequest defines model for BrowseRequest.
type BrowseRequest struct {
	SelectedTags *[]string `json:"selected_tags,omitempty"`
}

// BrowseResponse defines model for BrowseResponse.
type BrowseResponse struct {
	Tags         []Tag `json:"tags"`
	TotalMatches int   `json:"total_matches"`
}

// Comment defines model for Comment.
type Comment struct {
	Author      *string            `json:"author,omitempty"`
	Content     string             `json:"content"`
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	KnowledgeId openapi_types.UUID `json:"knowledge_id"`
	Processed   *bool              `json:"processed,omitempty"`
	ProcessedAt *time.Time         `json:"processed_at,omitempty"`
	Reasoning   string             `json:"reasoning"`
	Scenario    *string            `json:"scenario,omitempty"`
	Type        CommentType        `json:"type"`
}

// CommentRequest defines model for CommentRequest.
type CommentRequest struct {
	Author    *string     `json:"author,omitempty"`
	Content   string      `json:"content"`
	Reasoning string      `json:"reasoning"`
	Scenario  *string     `json:"scenario,omitempty"`
	Type      CommentType `json:"type"`
}

// CommentResponse defines model for CommentResponse.
type CommentResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// CommentStats defines model for CommentStats.
type CommentStats struct {
	Failure     *int `json:"failure,omitempty"`
	Total       *int `json:"total,omitempty"`
	Unprocessed *int `json:"unprocessed,omitempty"`
}

// CommentType defines model for CommentType.
type CommentType string

// CommentsSummary defines model for CommentsSummary.
type CommentsSummary struct {
	Correction *int `json:"correction,omitempty"`
	Failure    *int `json:"failure,omitempty"`
	Success    *int `json:"success,omitempty"`
	Supplement *int `json:"supplement,omitempty"`
}

// ConflictReport defines model for ConflictReport.
type ConflictReport struct {
	CommentIds   *[]string          `json:"comment_ids,omitempty"`
	CreatedAt    time.Time          `json:"created_at"`
	Description  string             `json:"description"`
	Id           openapi_types.UUID `json:"id"`
	KnowledgeIds *[]string          `json:"knowledge_ids,omitempty"`
	Resolution   *string            `json:"resolution,omitempty"`
	ResolvedAt   *time.Time         `json:"resolved_at,omitempty"`
	Status       ConflictStatus     `json:"status"`
	Type         ConflictType       `json:"type"`
}

// ConflictStatus defines model for ConflictStatus.
type ConflictStatus string

// ConflictType defines model for ConflictType.
type ConflictType string

// ContributeRequest defines model for ContributeRequest.
type ContributeRequest struct {
	Author  *string  `json:"author,omitempty"`
	Body    string   `json:"body"`
	Summary string   `json:"summary"`
	Tags    []string `json:"tags"`
	Title   string   `json:"title"`
}

// ContributeResponse defines model for ContributeResponse.
type ContributeResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// CreateConflictRequest defines model for CreateConflictRequest.
type CreateConflictRequest struct {
	CommentIds   *[]openapi_types.UUID `json:"comment_ids,omitempty"`
	Description  string                `json:"description"`
	KnowledgeIds []openapi_types.UUID  `json:"knowledge_ids"`
	Type         ConflictType          `json:"type"`
}

// CreateConflictResponse defines model for CreateConflictResponse.
type CreateConflictResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// CurationAction defines model for CurationAction.
type CurationAction string

// CurationLog defines model for CurationLog.
type CurationLog struct {
	Action      CurationAction     `json:"action"`
	AgentId     *string            `json:"agent_id,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Diff        *string            `json:"diff,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	SourceIds   *[]string          `json:"source_ids,omitempty"`
	TargetId    string             `json:"target_id"`
}

// CurationLogRequest defines model for CurationLogRequest.
type CurationLogRequest struct {
	Action      CurationAction `json:"action"`
	Description string         `json:"description"`
	Diff        *string        `json:"diff,omitempty"`
	SourceIds   *[]string      `json:"source_ids,omitempty"`
	TargetId    string         `json:"target_id"`
}

// CurationLogResponse defines model for CurationLogResponse.
type CurationLogResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// FlaggedEntry defines model for FlaggedEntry.
type FlaggedEntry struct {
	CommentStats *CommentStats      `json:"comment_stats,omitempty"`
	FlagReasons  []string           `json:"flag_reasons"`
	Id           openapi_types.UUID `json:"id"`
	NeedsRewrite *bool              `json:"needs_rewrite,omitempty"`
	Title        string             `json:"title"`
	Weight       *float64           `json:"weight,omitempty"`
}

// HighFreqTag defines model for HighFreqTag.
type HighFreqTag struct {
	Frequency int     `json:"frequency"`
	Name      string  `json:"name"`
	Share     float64 `json:"share"`
}

// KnowledgeDetail defines model for KnowledgeDetail.
type KnowledgeDetail struct {
	Author          *string            `json:"author,omitempty"`
	Body            *string            `json:"body,omitempty"`
	CommentsSummary *CommentsSummary   `json:"comments_summary,omitempty"`
	CreatedAt       time.Time          `json:"created_at"`
	Id              openapi_types.UUID `json:"id"`
	Summary         *string            `json:"summary,omitempty"`
	Tags            *[]string          `json:"tags,omitempty"`
	Title           string             `json:"title"`
	UpdatedAt       time.Time          `json:"updated_at"`
	Weight          *float64           `json:"weight,omitempty"`
}

// KnowledgeEntry defines model for KnowledgeEntry.
type KnowledgeEntry struct {
	AccessCount  *int               `json:"access_count,omitempty"`
	AccessedAt   *time.Time         `json:"accessed_at,omitempty"`
	AppendCount  *int               `json:"append_count,omitempty"`
	Author       *string            `json:"author,omitempty"`
	Body         *string            `json:"body,omitempty"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	NeedsRewrite *bool              `json:"needs_rewrite,omitempty"`
	Status       KnowledgeStatus    `json:"status"`
	Summary      *string            `json:"summary,omitempty"`
	Tags         *[]string          `json:"tags,omitempty"`
	Title        string             `json:"title"`
	UpdatedAt    time.Time          `json:"updated_at"`
	Weight       *float64           `json:"weight,omitempty"`
}

// KnowledgeStatus defines model for KnowledgeStatus.
type KnowledgeStatus string

// LowFreqTag defines model for LowFreqTag.
type LowFreqTag struct {
	Frequency int    `json:"frequency"`
	Name      string `json:"name"`
}

// MarkProcessedRequest defines model for MarkProcessedRequest.
type MarkProcessedRequest struct {
	CommentIds []openapi_types.UUID `json:"comment_ids"`
}

// MergeKnowledgeRequest defines model for MergeKnowledgeRequest.
type MergeKnowledgeRequest struct {
	MergedBody    string               `json:"merged_body"`
	MergedSummary string               `json:"merged_summary"`
	SourceIds     []openapi_types.UUID `json:"source_ids"`
	TargetId      openapi_types.UUID   `json:"target_id"`
}

// MergeKnowledgeResponse defines model for MergeKnowledgeResponse.
type MergeKnowledgeResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// MergeTagsRequest defines model for MergeTagsRequest.
type MergeTagsRequest struct {
	Sources []string `json:"sources"`
	Target  string   `json:"target"`
}

// MergeTagsResponse defines model for MergeTagsResponse.
type MergeTagsResponse struct {
	AffectedKnowledgeCount int `json:"affected_knowledge_count"`
}

// RecalculateResponse defines model for RecalculateResponse.
type RecalculateResponse struct {
	UpdatedCount int `json:"updated_count"`
}

// ResolveConflictRequest defines model for ResolveConflictRequest.
type ResolveConflictRequest struct {
	Resolution string `json:"resolution"`
}

// ReviewData defines model for ReviewData.
type ReviewData struct {
	Knowledge           KnowledgeEntry `json:"knowledge"`
	UnprocessedComments []Comment      `json:"unprocessed_comments"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Keyword *string   `json:"keyword,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Id      openapi_types.UUID `json:"id"`
	Summary *string            `json:"summary,omitempty"`
	Tags    *[]string          `json:"tags,omitempty"`
	Title   string             `json:"title"`
	Weight  *float64           `json:"weight,omitempty"`
}

// SimilarPair defines model for SimilarPair.
type SimilarPair struct {
	IdA          openapi_types.UUID `json:"id_a"`
	IdB          openapi_types.UUID `json:"id_b"`
	OverlapRatio float64            `json:"overlap_ratio"`
	OverlapTags  []string           `json:"overlap_tags"`
	TitleA       string             `json:"title_a"`
	TitleB       string             `json:"title_b"`
}

// SimilarTagPair defines model for SimilarTagPair.
type SimilarTagPair struct {
	Reason string   `json:"reason"`
	Tags   []string `json:"tags"`
}

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	ActiveKnowledge     *int `json:"active_knowledge,omitempty"`
	ArchivedKnowledge   *int `json:"archived_knowledge,omitempty"`
	OpenConflicts       *int `json:"open_conflicts,omitempty"`
	TotalComments       *int `json:"total_comments,omitempty"`
	TotalKnowledge      *int `json:"total_knowledge,omitempty"`
	TotalTags           *int `json:"total_tags,omitempty"`
	UnprocessedComments *int `json:"unprocessed_comments,omitempty"`
}

// Tag defines model for Tag.
type Tag struct {
	// Count Number of knowledge entries with this tag
	Count *int   `json:"count,omitempty"`
	Name  string `json:"name"`
}

// TagHealthReport defines model for TagHealthReport.
type TagHealthReport struct {
	HighFreq     *[]HighFreqTag    `json:"high_freq,omitempty"`
	LowFreq      *[]LowFreqTag     `json:"low_freq,omitempty"`
	SimilarPairs *[]SimilarTagPair `json:"similar_pairs,omitempty"`
}

// UpdateKnowledgeRequest defines model for UpdateKnowledgeRequest.
type UpdateKnowledgeRequest struct {
	Body    string   `json:"body"`
	Summary string   `json:"summary"`
	Tags    []string `json:"tags"`
	Title   string   `json:"title"`
}

// UpdateResponse defines model for UpdateResponse.
type UpdateResponse struct {
	UpdatedAt time.Time `json:"updated_at"`
}

// KnowledgeID defines model for KnowledgeID.
type KnowledgeID = openapi_types.UUID

// Error defines model for Error.
type Error = ErrorResponse

// SystemListConflictsParams defines parameters for SystemListConflicts.
type SystemListConflictsParams struct {
	Status *ConflictStatus `form:"status,omitempty" json:"status,omitempty"`
}

// SystemListCurationLogsParams defines parameters for SystemListCurationLogs.
type SystemListCurationLogsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SystemListKnowledgeParams defines parameters for SystemListKnowledge.
type SystemListKnowledgeParams struct {
	Status *KnowledgeStatus `form:"status,omitempty" json:"status,omitempty"`
	Tag    *string          `form:"tag,omitempty" json:"tag,omitempty"`
	Limit  *int             `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int             `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminMarkProcessedJSONRequestBody defines body for AdminMarkProcessed for application/json ContentType.
type AdminMarkProcessedJSONRequestBody = MarkProcessedRequest

// AdminCreateConflictJSONRequestBody defines body for AdminCreateConflict for application/json ContentType.
type AdminCreateConflictJSONRequestBody = CreateConflictRequest

// AdminLogCurationJSONRequestBody defines body for AdminLogCuration for application/json ContentType.
type AdminLogCurationJSONRequestBody = CurationLogRequest

// AdminMergeKnowledgeJSONRequestBody defines body for AdminMergeKnowledge for application/json ContentType.
type AdminMergeKnowledgeJSONRequestBody = MergeKnowledgeRequest

// AdminUpdateKnowledgeJSONRequestBody defines body for AdminUpdateKnowledge for application/json ContentType.
type AdminUpdateKnowledgeJSONRequestBody = UpdateKnowledgeRequest

// AdminMergeTagsJSONRequestBody defines body for AdminMergeTags for application/json ContentType.
type AdminMergeTagsJSONRequestBody = MergeTagsRequest

// AgentBrowseJSONRequestBody defines body for AgentBrowse for application/json ContentType.
type AgentBrowseJSONRequestBody = BrowseRequest

// AgentContributeJSONRequestBody defines body for AgentContribute for application/json ContentType.
type AgentContributeJSONRequestBody = ContributeRequest

// AgentAppendKnowledgeJSONRequestBody defines body for AgentAppendKnowledge for application/json ContentType.
type AgentAppendKnowledgeJSONRequestBody = AppendRequest

// AgentCommentJSONRequestBody defines body for AgentComment for application/json ContentType.
type AgentCommentJSONRequestBody = CommentRequest

// AgentSearchJSONRequestBody defines body for AgentSearch for application/json ContentType.
type AgentSearchJSONRequestBody = SearchRequest

// SystemResolveConflictJSONRequestBody defines body for SystemResolveConflict for application/json ContentType.
type SystemResolveConflictJSONRequestBody = ResolveConflictRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Batch mark comments as processed
	// (POST /api/v1/admin/comments/processed)
	AdminMarkProcessed(w http.ResponseWriter, r *http.Request)
	// Create a conflict report
	// (POST /api/v1/admin/conflicts)
	AdminCreateConflict(w http.ResponseWriter, r *http.Request)
	// Write a curation log entry
	// (POST /api/v1/admin/curation-logs)
	AdminLogCuration(w http.ResponseWriter, r *http.Request)
	// List knowledge entries needing review
	// (GET /api/v1/admin/flagged)
	AdminListFlagged(w http.ResponseWriter, r *http.Request)
	// Merge knowledge entries
	// (POST /api/v1/admin/knowledge/merge)
	AdminMergeKnowledge(w http.ResponseWriter, r *http.Request)
	// Find similar knowledge pairs by tag overlap
	// (GET /api/v1/admin/knowledge/similar)
	AdminFindSimilar(w http.ResponseWriter, r *http.Request)
	// Full update of knowledge entry (admin rewrite)
	// (PUT /api/v1/admin/knowledge/{id})
	AdminUpdateKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Archive knowledge entry (soft delete)
	// (POST /api/v1/admin/knowledge/{id}/archive)
	AdminArchive(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Get knowledge review details with unprocessed comments
	// (GET /api/v1/admin/knowledge/{id}/review)
	AdminGetReview(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Tag health report (synonyms, low/high frequency)
	// (GET /api/v1/admin/tags/health)
	AdminTagHealth(w http.ResponseWriter, r *http.Request)
	// Merge source tags into target tag
	// (POST /api/v1/admin/tags/merge)
	AdminMergeTags(w http.ResponseWriter, r *http.Request)
	// Faceted browsing - drill down by tags
	// (POST /api/v1/agent/browse)
	AgentBrowse(w http.ResponseWriter, r *http.Request)
	// Contribute new knowledge
	// (POST /api/v1/agent/knowledge)
	AgentContribute(w http.ResponseWriter, r *http.Request)
	// Read full knowledge entry (updates access stats)
	// (GET /api/v1/agent/knowledge/{id})
	AgentReadKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Append content to knowledge entry
	// (POST /api/v1/agent/knowledge/{id}/append)
	AgentAppendKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Add a comment to knowledge entry
	// (POST /api/v1/agent/knowledge/{id}/comments)
	AgentComment(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Search knowledge by tags and keyword
	// (POST /api/v1/agent/search)
	AgentSearch(w http.ResponseWriter, r *http.Request)
	// List conflict reports
	// (GET /api/v1/system/conflicts)
	SystemListConflicts(w http.ResponseWriter, r *http.Request, params SystemListConflictsParams)
	// Resolve a conflict report
	// (POST /api/v1/system/conflicts/{id}/resolve)
	SystemResolveConflict(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List curation logs
	// (GET /api/v1/system/curation-logs)
	SystemListCurationLogs(w http.ResponseWriter, r *http.Request, params SystemListCurationLogsParams)
	// List knowledge entries with filters
	// (GET /api/v1/system/knowledge)
	SystemListKnowledge(w http.ResponseWriter, r *http.Request, params SystemListKnowledgeParams)
	// Hard delete knowledge entry (permanent)
	// (DELETE /api/v1/system/knowledge/{id})
	SystemDeleteKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Read knowledge entry (no access stat update)
	// (GET /api/v1/system/knowledge/{id})
	SystemGetKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Restore archived knowledge entry
	// (POST /api/v1/system/knowledge/{id}/restore)
	SystemRestoreKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID)
	// Batch recalculate all knowledge weights
	// (POST /api/v1/system/recalculate-weights)
	SystemRecalculateWeights(w http.ResponseWriter, r *http.Request)
	// System status overview
	// (GET /api/v1/system/status)
	SystemGetStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Batch mark comments as processed
// (POST /api/v1/admin/comments/processed)
func (_ Unimplemented) AdminMarkProcessed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a conflict report
// (POST /api/v1/admin/conflicts)
func (_ Unimplemented) AdminCreateConflict(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Write a curation log entry
// (POST /api/v1/admin/curation-logs)
func (_ Unimplemented) AdminLogCuration(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List knowledge entries needing review
// (GET /api/v1/admin/flagged)
func (_ Unimplemented) AdminListFlagged(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Merge knowledge entries
// (POST /api/v1/admin/knowledge/merge)
func (_ Unimplemented) AdminMergeKnowledge(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Find similar knowledge pairs by tag overlap
// (GET /api/v1/admin/knowledge/similar)
func (_ Unimplemented) AdminFindSimilar(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Full update of knowledge entry (admin rewrite)
// (PUT /api/v1/admin/knowledge/{id})
func (_ Unimplemented) AdminUpdateKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Archive knowledge entry (soft delete)
// (POST /api/v1/admin/knowledge/{id}/archive)
func (_ Unimplemented) AdminArchive(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get knowledge review details with unprocessed comments
// (GET /api/v1/admin/knowledge/{id}/review)
func (_ Unimplemented) AdminGetReview(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Tag health report (synonyms, low/high frequency)
// (GET /api/v1/admin/tags/health)
func (_ Unimplemented) AdminTagHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Merge source tags into target tag
// (POST /api/v1/admin/tags/merge)
func (_ Unimplemented) AdminMergeTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Faceted browsing - drill down by tags
// (POST /api/v1/agent/browse)
func (_ Unimplemented) AgentBrowse(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Contribute new knowledge
// (POST /api/v1/agent/knowledge)
func (_ Unimplemented) AgentContribute(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read full knowledge entry (updates access stats)
// (GET /api/v1/agent/knowledge/{id})
func (_ Unimplemented) AgentReadKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Append content to knowledge entry
// (POST /api/v1/agent/knowledge/{id}/append)
func (_ Unimplemented) AgentAppendKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a comment to knowledge entry
// (POST /api/v1/agent/knowledge/{id}/comments)
func (_ Unimplemented) AgentComment(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search knowledge by tags and keyword
// (POST /api/v1/agent/search)
func (_ Unimplemented) AgentSearch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List conflict reports
// (GET /api/v1/system/conflicts)
func (_ Unimplemented) SystemListConflicts(w http.ResponseWriter, r *http.Request, params SystemListConflictsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve a conflict report
// (POST /api/v1/system/conflicts/{id}/resolve)
func (_ Unimplemented) SystemResolveConflict(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List curation logs
// (GET /api/v1/system/curation-logs)
func (_ Unimplemented) SystemListCurationLogs(w http.ResponseWriter, r *http.Request, params SystemListCurationLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List knowledge entries with filters
// (GET /api/v1/system/knowledge)
func (_ Unimplemented) SystemListKnowledge(w http.ResponseWriter, r *http.Request, params SystemListKnowledgeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Hard delete knowledge entry (permanent)
// (DELETE /api/v1/system/knowledge/{id})
func (_ Unimplemented) SystemDeleteKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read knowledge entry (no access stat update)
// (GET /api/v1/system/knowledge/{id})
func (_ Unimplemented) SystemGetKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore archived knowledge entry
// (POST /api/v1/system/knowledge/{id}/restore)
func (_ Unimplemented) SystemRestoreKnowledge(w http.ResponseWriter, r *http.Request, id KnowledgeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Batch recalculate all knowledge weights
// (POST /api/v1/system/recalculate-weights)
func (_ Unimplemented) SystemRecalculateWeights(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// System status overview
// (GET /api/v1/system/status)
func (_ Unimplemented) SystemGetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdminMarkProcessed operation middleware
func (siw *ServerInterfaceWrapper) AdminMarkProcessed(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminMarkProcessed(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminCreateConflict operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateConflict(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminCreateConflict(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminLogCuration operation middleware
func (siw *ServerInterfaceWrapper) AdminLogCuration(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminLogCuration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListFlagged operation middleware
func (siw *ServerInterfaceWrapper) AdminListFlagged(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListFlagged(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminMergeKnowledge operation middleware
func (siw *ServerInterfaceWrapper) AdminMergeKnowledge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminMergeKnowledge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminFindSimilar operation middleware
func (siw *ServerInterfaceWrapper) AdminFindSimilar(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminFindSimilar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUpdateKnowledge operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUpdateKnowledge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminArchive operation middleware
func (siw *ServerInterfaceWrapper) AdminArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminArchive(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminGetReview operation middleware
func (siw *ServerInterfaceWrapper) AdminGetReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminGetReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminTagHealth operation middleware
func (siw *ServerInterfaceWrapper) AdminTagHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminTagHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminMergeTags operation middleware
func (siw *ServerInterfaceWrapper) AdminMergeTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminMergeTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AgentBrowse operation middleware
func (siw *ServerInterfaceWrapper) AgentBrowse(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgentBrowse(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AgentContribute operation middleware
func (siw *ServerInterfaceWrapper) AgentContribute(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgentContribute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AgentReadKnowledge operation middleware
func (siw *ServerInterfaceWrapper) AgentReadKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgentReadKnowledge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AgentAppendKnowledge operation middleware
func (siw *ServerInterfaceWrapper) AgentAppendKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgentAppendKnowledge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AgentComment operation middleware
func (siw *ServerInterfaceWrapper) AgentComment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgentComment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AgentSearch operation middleware
func (siw *ServerInterfaceWrapper) AgentSearch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgentSearch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemListConflicts operation middleware
func (siw *ServerInterfaceWrapper) SystemListConflicts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SystemListConflictsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemListConflicts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemResolveConflict operation middleware
func (siw *ServerInterfaceWrapper) SystemResolveConflict(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemResolveConflict(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemListCurationLogs operation middleware
func (siw *ServerInterfaceWrapper) SystemListCurationLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SystemListCurationLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemListCurationLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemListKnowledge operation middleware
func (siw *ServerInterfaceWrapper) SystemListKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SystemListKnowledgeParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemListKnowledge(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemDeleteKnowledge operation middleware
func (siw *ServerInterfaceWrapper) SystemDeleteKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemDeleteKnowledge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemGetKnowledge operation middleware
func (siw *ServerInterfaceWrapper) SystemGetKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemGetKnowledge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemRestoreKnowledge operation middleware
func (siw *ServerInterfaceWrapper) SystemRestoreKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id KnowledgeID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemRestoreKnowledge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemRecalculateWeights operation middleware
func (siw *ServerInterfaceWrapper) SystemRecalculateWeights(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemRecalculateWeights(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemGetStatus operation middleware
func (siw *ServerInterfaceWrapper) SystemGetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemGetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/comments/processed", wrapper.AdminMarkProcessed)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/conflicts", wrapper.AdminCreateConflict)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/curation-logs", wrapper.AdminLogCuration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/flagged", wrapper.AdminListFlagged)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/knowledge/merge", wrapper.AdminMergeKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/knowledge/similar", wrapper.AdminFindSimilar)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/admin/knowledge/{id}", wrapper.AdminUpdateKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/knowledge/{id}/archive", wrapper.AdminArchive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/knowledge/{id}/review", wrapper.AdminGetReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/tags/health", wrapper.AdminTagHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/tags/merge", wrapper.AdminMergeTags)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/agent/browse", wrapper.AgentBrowse)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/agent/knowledge", wrapper.AgentContribute)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/agent/knowledge/{id}", wrapper.AgentReadKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/agent/knowledge/{id}/append", wrapper.AgentAppendKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/agent/knowledge/{id}/comments", wrapper.AgentComment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/agent/search", wrapper.AgentSearch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/system/conflicts", wrapper.SystemListConflicts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/system/conflicts/{id}/resolve", wrapper.SystemResolveConflict)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/system/curation-logs", wrapper.SystemListCurationLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/system/knowledge", wrapper.SystemListKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/system/knowledge/{id}", wrapper.SystemDeleteKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/system/knowledge/{id}", wrapper.SystemGetKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/system/knowledge/{id}/restore", wrapper.SystemRestoreKnowledge)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/system/recalculate-weights", wrapper.SystemRecalculateWeights)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/system/status", wrapper.SystemGetStatus)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+QcWW/cNvqvENp9aIBJxmm7QDFvadMcaHYRxF70ITAGtPSNho0kKiTl2UEw/33BQxIp",
	"URLn0DiLfbMtHt9909+imOYlLaAQPFp9i0rMcA4CmPrtj4LuMkhSeP9a/kqKaBWVWGyjRVTgHKJVRJJo",
	"ETH4WhEGSbQSrIJFxOMt5Fju2FCWYxGtoqpSK8W+lLu4YKRIo8PhIDfzkhYc1IW/M0aZ/CGmhYBCyB9x",
	"WWYkxoLQYvkXp4X8W3vD3xlsolX0t2WLx1J/5Ut12idzvr4tAR4zUsrDopW+DrF2RQ27AuZVWUKRfIKv",
	"FXAFScloCUwQDasFYgetGs9x6PTxd3KlpkNNxM96+6K54b4hHH34C2Ihb6iBM6D3oMPq+zqmlQMiKQSk",
	"wOQJJAnhkAuYWuIcPQzbnaEBFFUu9/KqLDPIJUISNcYgVmy4X/Tp9yujOw6DpOeQQSwgWQucqj8QATkf",
	"4USEGcN7hU4P2vquIUr27hhj6h323LqIBBU4W+dYxFvgPnZ0BUDe2d3mI/VvNM+NEHb4X4mtVqUeScYE",
	"N2aAJWGxcIQjwQKeC5JD5GFWkCAtoi+1MVkHbigZjYFzSCxIHyjNABfO56OAZYA5LeQvPvR5DAVmhJ6s",
	"1IYfXq1WWDpUWHQ13YbPYcYI7we15EQReEIKjVBjlABDqnuiiRu561Zg4yidizaYZBUDv6FVWuz/VBU+",
	"IbetwhAgfesay3OiRQPL4iiLa47lt1WeY7b3ubtmvxeVURLU0A18bMAMpkGxyUgsPkFJmdc1K2TWJDnK",
	"O5xm/pyQ4ttFzOORUDPgNKsGAVCfH4/EigssKj6tzJoRt3p1sAnQu4atpDEENmkbkALsogOUpSS0hCJq",
	"CTKgCBZw1t5W/texWeKY8+aPA4cKRh4qAadY6wea7P3GuFXWvpBMhkY5Kd7rjy89EQsRGXi2dS22WtZC",
	"YoA11w9wpyHFNey2kpXWYAwG836LMam2XbpNWYNhNZ+8apxf5+qdUTkXPhefEPpeg6UVU9ngq8Yb1Tqa",
	"A0th7bg9mT3u15bzWkQJ3RUpw4lEF7N4Sx7lT3qvCbz1Lw0tGpszoeUGsA809eh3A+0oi1zcDosIp1ou",
	"LxauT0loQjabcxwZpxWLT/BiArMUBjD1pqE1P9uNXY8x5Shafg2b5RPZdjKVr0C+ScpNEusKWu4WbzwG",
	"OxmINXPgHKcBvksd0a73AfEmw2kKye+F8IfE2mnwOikIyHt0AiHj5Qyna53fHMnpQD0sABK+ZrBjRIA/",
	"hR5y8otoByTddowKrR4yy6IUVf7gKV1oYExY4CDpI/A7km7fMPh6hz0mcyPPhSLe+xmtS5A+FdpinYgc",
	"C7s6cWHdW5/lA70pjr4GgUl2mYjOiBRfW6FdgFQ1adu8JZzz4s3QEHMRVWVyNAoXkliLeg4coxIwYB+w",
	"SnrHarB6xZGYTpd2T5K8+cQmwBKFpZsNwdt88/9AJH15b7hs9rNg6f4freDXnwd/oLsLG+YpY+tD45+Y",
	"fflYl8gun72NpFS9YKG9wguozBgaog9CqhKLZD2oheb7mFQPBIhnpo929Hhc/GYHkRZsCwfXHmYhNLxC",
	"lKmuvMMpH+41KZTOKqUoAgXUUvS6RXPlBMCDrb/NRnfH7OJUNVhddTKDoa0+UD5BjLO4yvBYKac2U6EQ",
	"uOv916rq3WRJZ7Qq2rnVWuu/8pHA7jUWuH9NWyQIdV46WnCr/+s68AvuNNadv8OE4bKLGN4LfQjfgvQN",
	"g6T9AvsdZclFnO5h5HpeZeJE9b9eZHARL+9lAslJhtlHTJiPCGscRAaSrB+CFtJHYBku1yrND0Kn3XMi",
	"PTUK/bXq20NIHWiNo/Ysg2x7QAfALo4jRL/DqZ/uOpk9teKO/2PcxI+2z/hxQoUN8OZqL9R7LiBvQ71+",
	"DevRLmf6kwYTDU6toyW0LRA+0vJ0bNrQmonL9KKasqMN1NHrfFbGG9o2fsqdFPqXEnlEN6gBGEEhGAGO",
	"dkRskdgSjgROWy05LSC+9wP6DnAmtkP9zi1Jt2sZSAd7D7vu4tHOjO6OO8/KFjzHca1U6xITFu7hOqoY",
	"5Dn+rcKH6Th8ppba1bpoGs/psCs8XR2Iw7zppVxMig3t68mrFAph6QjfYnk8KjMsJBToOXr18T26BfYI",
	"rPF+qzZdRe+qB7kkWkSPwLg+9ebFyxc3te3BJYlW0U8vbl78FC3UOKLCeIlLsnx8ucRJToplbQuWznxF",
	"SbUsSEqpYvb7RMIsdziJpplpBC5+NXJykXlEbzJ7cCkvWAXdqcgfb26OgsHDLZdLddUQ5Zh9gQRhjlo6",
	"qdUbbEIvHz4NcHrCUs9N1noT/YpFvFUno5oL7gW1In2OFK+ie7m/yz7LvYxwze0+zsQ2fws5iG8vZwNi",
	"eKi1XoOY8hbIVI3O5quGAGEUuxcE8dM0j55nNJ3i6Qea1r2muRja7/tdm5ueZpqPlWYZymh6MT7+yYhm",
	"o304qJw0gJMb3RGTV5uiho+FhAvTOovOtGVBkYLTpuvHCT26mvV1BHc2SSW+nsCwAEik82OqfBBC3eaM",
	"pSqXTfksp142l9PyFjZn8FrHADGsMm0goQuOZ/NWXd1n7nHcNAHwuNa8IUViYt6raI1dXwhQGrPcIoUO",
	"588lsEQbcf/h6GEvkypk8vbjiP6NJAelQdUQxTvZggon2/cvn/3YtEuW9vuYw/08+jeQ0VxZATv5xqji",
	"mdRBCsbPNz8HC8W5YlRlmbm6n6bv0Q9KOpBpQj47XpKW9ajYuE1+1QyUnStKcyYAylOipv93Lu0N0n2i",
	"c7oRKIEMTiO5cZyjVvMtiE+1f31Cko8pj9U+8PBCf0WJ+nxVlXkLdtTCDBxqmsVUtazyWpPMhfBRLlhu",
	"Vc1qnHtNaSuakf7d+pmHCXc4RRreOqs5l7i9E9EPfF/QYp/zBcrobrkl6RY13e9nwWQNjgzv6rLxTEGh",
	"3TZ9injQ6YL6ecovGwXqxqyMSDgihaBIt2zruu8I+1IoxPJBvTQcYZ1cpZ8jzsQ3913llZnWeWg5oIUb",
	"HIPgiDKk3j3K/OlSadobeTQkSPFBHvwcJYxkGUrorjChpmPeUvX6ts9Ip2kxwsv2rcNclYzeu5JrFzL6",
	"rzlGY8OLFaOae1EBO2Q3ucO512QIfv+UqreFOLlkfjCTanVnUX01Dxkft94+MQuvGnBIaqKNC4iJFHXk",
	"zpGeiERqpPrZ8dxc6uHICb3UD9S/77zP/e8DVzbVnf8u4K8yy2uQpvfVsz0NIDLIIkG7EnWC6Nj941Gj",
	"npu3Rd+f0HSehF/dGbjvsYc7T7YfuKbUJInqX2gYThMarmaTJmREDzDN5PTd4awZLENY9dCe0QopH6r1",
	"iKkNHHHKVCi2R2Z+6lzemvNbjpp4DuEiQfXA2ih/uRqicXuP3shAT9t8IFz81qztWQP1z3K+VqCkyvy3",
	"nGaSOzi4cl5Xnx1CBA4WOo/rA1jb6TheqJ8Sd09tmac5Nc69uoKkhkWH1VXzsjNTOsDNi/7ro5k8wMB0",
	"7NNMGTQMNO/tz48f1UGjPegx2eh2oae0u+3SBip4RnIiHP1u8P3HTX8y7EoKbT1LDtFmqy98KVV2jgzi",
	"lZNiT/BpJJC/gBXuPTo6LPzn6ipQT0HaAavLyMzAMXSz4TBwzpOJXn/mfUr6/uh10TPCxVwdelXk3pBM",
	"yctxctkUD3R7Y0g+X6uvs5UQfu6P4Onejobq2gH2O8wSc3U/xS+B5Vie8sxH6sWYlr8F8b9UhTHSPiXd",
	"+6cov/TYUlC76GJaqM9O0QZ5vaAsJNqSy74TjgY2Sw1uFwli5EFN93UkCR2hPGsfXz3XGRSfJnuz5U+z",
	"Y9amZ/91mIe4BhJk4XOpEVTrSISdmuOuQT+A0u3T5HEDdVuHFbOR1Hnl4Uux1XfEm8fR5yXU9mlqAqcz",
	"xdbSTO5TE91ae12oPtAYZyiBR8hoqQovvJ7+rlgWraKtEOVquczkui3lYvXyl5tfbqLD/eG/AQAA//9b",
	"eLwZnlYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
